laravel/cashier-paddle

src/Concerns/Prorates.php
=> Add a setProration method

src/Cashier.php, src/CashierServiceProvider.php, src/Http/Controllers/WebhookController.php, src/Http/Middleware/VerifyWebhookSignature.php, src/Subscription.php, tests/Feature/WebhooksTest.php
Replaces https://github.com/laravel/cashier-paddle/pull/42
=> Extract webhookcontroller methods

src/Receipt.php
PR for this issue: https://github.com/laravel/cashier-paddle/issues/48
=> Fix receipt relation with subscription

src/Events/PaymentSucceeded.php, src/Events/SubscriptionCancelled.php, src/Events/SubscriptionCreated.php, src/Events/SubscriptionPaymentFailed.php, src/Events/SubscriptionPaymentSucceeded.php, src/Events/SubscriptionUpdated.php, src/Http/Controllers/WebhookController.php
* Added missing `payload` param to phpdoc
* Dispatch subscription payment failed events too
=> [1.x] Event Improvements

src/Concerns/ManagesSubscriptions.php
Equivalent of https://github.com/laravel/cashier-stripe/pull/1009
=> [1.x] Fix n+1 problem with subscription retrieval

.github/workflows/tests.yml, composer.json
Blocked by https://github.com/spatie/url/pull/39 atm.
=> [1.x] PHP 8 Support

.github/workflows/tests.yml, composer.json
Drop PHP 7.2 support for the next major release.
=> [2.x] Drop PHP 7.2 support

src/Cashier.php, src/Concerns/ManagesCustomer.php, src/Concerns/ManagesReceipts.php, src/Concerns/ManagesSubscriptions.php, src/Http/Controllers/WebhookController.php, src/Receipt.php, src/Subscription.php
Allows people to swap the base models in the same fashion as Passport & Sanctum.
=> [1.x] Allow custom models

.github/workflows/tests.yml, composer.json
Drop Laravel 7 support for the next major release.
=> [2.x] Drop Laravel 7 support

resources/views/js.blade.php
change url paddle if using sandbox mode
=> [1.x] Update environment sandbox Paddle.js

src/Price.php, tests/Unit/ProductPriceTest.php
This PR cherry picks #126 which was accidentally sent in to master instead of 1.x
=> [1.x] Add hasTax

.github/workflows/tests.yml, composer.json
=> Laravel 9 Support

src/Payment.php, tests/Feature/PaymentTest.php
=> Allow to serialize payment object

src/Cashier.php, tests/Unit/CashierTest.php
Cashier Paddle equivalent of https://github.com/laravel/cashier-stripe/pull/1348
=> Add options to formatAmount

.github/workflows/tests.yml, UPGRADE.md, composer.json
Drop support for old PHP and Laravel versions for the next major release.
=> Drop old versions

src/Concerns/ManagesSubscriptions.php, src/Customer.php, src/Subscription.php, tests/Unit/CustomerTest.php, tests/Unit/SubscriptionTest.php
Equivalent of https://github.com/laravel/cashier-stripe/pull/1366
=> Add trial expired methods

database/migrations/2019_05_03_000001_create_customers_table.php, database/migrations/2019_05_03_000002_create_subscriptions_table.php, database/migrations/2019_05_03_000003_create_receipts_table.php
=> [2.x] Modernize migrations

database/migrations/2019_05_03_000001_create_customers_table.php, database/migrations/2019_05_03_000002_create_subscriptions_table.php, database/migrations/2019_05_03_000003_create_receipts_table.php
Please check https://github.com/laravel/laravel/pull/6010 for details about this pull request.
=> [1.x] Uses PHP Native Type Declarations 🐘 

.gitattributes, .github/workflows/static-analysis.yml, composer.json, phpstan.neon.dist, src/ProductPrice.php
This pull request adds basic type checking to this repository.
=> [1.x] Adds type checking

src/Cashier.php, src/Modifier.php, src/Payment.php, src/Price.php, src/Receipt.php
This is a little bit more expressive @driesvints. 🤷🏻
=> Move the logic into a Cashier static method

.github/workflows/tests.yml, composer.json
Because of a change in Guzzle/promises.
=> Drop PHP 7.2 & 7.3 and Laravel 7

.github/workflows/tests.yml, composer.json
=> [2.x] Drop Laravel v9 and PHP 8.0

.github/workflows/tests.yml, .gitignore, composer.json, phpunit.xml.dist, tests/Feature/FeatureTestCase.php
=> [2.x] Use PHPUnit 10

README.md
Moves the current live docs to the 1.x branch
=> Move 1.x docs to GitHub repo

src/Http/Controllers/WebhookController.php, src/Transaction.php, tests/Feature/WebhooksTest.php
- Fixed and issue with variable assignment
- Added transaction status constants, pulled from here: https://developer.paddle.com/webhooks/transactions/transaction-updated
- Added transaction updated webhook test
- Some comment fixes
Let me know if I missed something
=> Fix transaction updated webhook handler

README.md, src/Components/Checkout.php, src/Subscription.php
- fix resuming subscriptions
- Re-add the docs for lastPayment and nextPayment
=> Some fixes for Cashier Paddle v2
