laravel/cashier-paddle

src/Concerns/PerformsCharges.php
Hi @driesvints,
The billable model could be different from user, let's use the value of the model's primary key instead. Thoughts?
Thanks,
=> Use primary key as customer ID

src/Subscription.php, tests/Feature/SubscriptionsTest.php, tests/Unit/ProductPriceTest.php, tests/Unit/TransactionTest.php
Unfortunately Paddle doesn't allows this so it's best to prevent the request from happening.
Also fixes some tests.
=> Prevent swapping during trial

src/Subscription.php
This will remove the subscription out of the grace period rightaway so we don't have to wait for the webhook.
=> Reset pause state after unpausing

database/migrations/2019_05_03_000002_create_subscriptions_table.php, src/Http/Controllers/WebhookController.php, src/Subscription.php
Paddle doesn't has a webhook to inform us when the payment information was updated so we'll have to read the info directly from the endpoint.
=> Use endpoint for card info

src/ProductPrice.php, tests/Unit/ProductPriceTest.php
This PR adds some new methods for the prices api. Additional to the current `price` and `listPrice` method this PR introduces the following new ones:
- `initialPrice`: alias of `price` but better terminology for subscriptions plans
- `initialListPrice`: alias of `listPrice` but better terminology for subscriptions plans
- `recurringPrice`: the recurring amount each interval for subscription plans
- `recurringListPrice`: the originally listed amount each interval for subscription plans
This PR also adds some convenience methods to get information about subscription plans which can be used to display in UI:
- `planTrialDays`
- `planInterval`
- `planFrequency`
=> Implement new prices

database/migrations/2019_05_03_000001_create_customers_table.php, src/Concerns/ManagesCustomer.php, src/Concerns/ManagesSubscriptions.php, src/Http/Controllers/WebhookController.php, tests/Feature/CustomerTest.php, tests/Feature/FeatureTestCase.php
This PR will allow people to create customer records in advance of any subscriptions or one-time product charges being made. This will allow them to use the trial without card up front feature. See https://github.com/laravel/cashier-paddle/pull/18#discussion_r445776921
Ping @stefanzweifel
=> Allow to create empty customer

database/migrations/2019_05_03_000002_create_subscriptions_table.php, src/Concerns/ManagesSubscriptions.php, src/Customer.php, src/Http/Controllers/WebhookController.php, src/Subscription.php, src/Transaction.php, tests/Feature/CustomerTest.php, tests/Feature/SubscriptionsTest.php, tests/Feature/TransactionsTest.php
This will make it easier to access subscriptions from the billable model. All subscription based methods are now removed from the `Customer` model. They can always be accessed through the billable model.
Now you can apply scopes on subscriptions from the billable model:
```php
$user->subscriptions()->active()->get();
```
In an ideal later scenario we'd have a custom relationship so accessing the subscriptions can be done through the `Customer` model and the database scheme would be safer (direct relationships) and simpler. But for now this is a good intermediate solution.
=> Refactor to polymorphic subscriptions

src/Http/Controllers/WebhookController.php, tests/Feature/WebhooksTest.php
The current `master`-version of the package doesn't update an existing customer with `paddle_id` and `paddle_email` when a user subscribes to a plan.
My app is responsible for trial-periods and creates a new customer during registration. Subscribing to a plan in this scenario would not add the `paddle_id` to the customer which in turn breaks `$user->transactions()`.
```php
$user->createAsCustomer([
'trial_ends_at' => now('UTC')->addDays(14),
]);
```
=> Update possible existing Customer with paddle_id

src/Http/Controllers/WebhookController.php, tests/Feature/WebhooksTest.php
Fixes a bug with a wrong referenced `quantity` parameter and removes the checks from the `cancellation_effective_date` parameter which is always set.
Fixes https://github.com/laravel/cashier-paddle/issues/41
=> Fix webhook controller

src/Events/PaymentSucceeded.php, src/Events/SubscriptionCancelled.php, src/Events/SubscriptionCreated.php, src/Events/SubscriptionPaymentSucceeded.php, src/Events/SubscriptionUpdated.php, src/Http/Controllers/WebhookController.php, tests/Feature/WebhooksTest.php
This PR adds events dedicated to existing webhook methods with the goal of abstracting Paddle also on the webhook layer, and making hooking into Cashier events easier & more expressive.
- Benefit for developers: No need to look into the Paddle documentation when trying to hook into Cashier events, less and more expressive code
- Does not break exiting features because: Existing, "raw" events have not been deleted. Events were added only.
- Tests: extended
=> Update webhook events to be more expressive

src/Concerns/ManagesSubscriptions.php, tests/Feature/SubscriptionsTest.php
PR adds a `trialEndsAt` function to the `Billable` trait.
This allows you to write code like this:
```
@if ($user->onTrial())
Your trial ends at {{ $user->trialEndsAt() }}.
@endif
```
Without this you'd first have to check whether the trial is generic or tied to a subscription.
It also lets you pass in a subscription name as the parameter (`$user->trialEndsAt('main')`).
=> [1.x] Added function to see when the trial is ending

src/Concerns/PerformsCharges.php
This will allow developers to override some customer settings through the options of various method calls that generate pay links.
=> [1.x] Allow payload override

src/Http/Controllers/WebhookController.php
Inside the ```handleSubscriptionPaymentFailed``` method the event signature was not imported.
=> [1.x] Missing use statement for SubscriptionPaymentFailed

src/Concerns/ManagesSubscriptions.php, tests/Feature/CustomerTest.php
Fixes #85 
Currently the `trialEndsAt` method checks if the user is on a generic trial. If it is then `trial_ends_at` on the User table will be returned. If it's not the trial of a subscription record will be returned.
This means that if a user used to be on a generic trial which is now expired, it will look for a (non-existent) subscription record instead of the `trial_ends_at` field and throw an exception.
With this PR `trialEndsAt` will check if there is a subscription. If there is not a subscription it will return the date from the `trial_ends_at` field. If there is a subscription, it will return the subscription.
=> [1.x] Fix trial ends at

src/Exceptions/InvalidPassthroughPayload.php, src/Http/Controllers/WebhookController.php, tests/Feature/WebhooksTest.php
This PR fixes a use case where people create manual paylinks from the Paddle dashboard. At least this way webhooks won't throw errors and they can do that. But of course no data will be synced in the app database since there's no way of knowing which type of subscription was created or to which customer the paylink belonged to.
Fixes https://github.com/laravel/cashier-paddle/issues/75
=> [1.x] Ignore manual paylinks

src/Http/Controllers/WebhookController.php
This fixes a bug with `cancelNow` where the incoming webhook from Paddle would sometimes overwrite the `Carbon::now()` timestamp from the `cancelNow` method. We're checking if the `ends_at` attribute hasn't been filled out yet before proceeding. Since it's impossible to restart cancelled subscriptions in Paddle we should be good with just this change.
Fixes https://github.com/laravel/cashier-paddle/issues/92
=> [1.x] Fix bug with cancelNow

src/Subscription.php
This fixes a bug where cancelling paused subscriptions was still trying to retrieve the next payment date as an end date. Because there's no next payment date for paused subscriptions this was failing. The fix now uses the start of the pause date as the new end date.
Also contains a small refactor to simplify the logic of cancelling subscriptions and prevent code duplication.
Fixes https://github.com/laravel/cashier-paddle/issues/100
=> [1.x] Fix cancel subscription

src/Subscription.php
This is a follow up for https://github.com/laravel/cashier-paddle/pull/101. ~I realised it actually makes more sense to cancel the subscription immediately when a customer explicitly cancels a paused subscription.~
Now sets the ends_at timestamp correctly when the subscription was paused in the past.
=> [1.x] Use cancel now when cancelling paused subscriptions

src/Concerns/PerformsCharges.php
Code checks for a maximum length of 100 on the `title` attribute while according to [the docs](https://developer.paddle.com/api-reference/product-api/pay-links/createpaylink) 200 characters are allowed.
=> [1.x] Fix too strict code on API call

src/Concerns/PerformsCharges.php
When trailing white spaces occurs on values for the pay link's payload, Laravel will strip these with the `TrimStrings` middleware and thus the signature verification from Paddle will fail. It's best that we trim all strings before generating the pay link. 
Fixes https://github.com/laravel/cashier-paddle/issues/120
=> [1.x] Trim whitespace for pay link values

src/Concerns/ManagesSubscriptions.php, tests/Feature/SubscriptionsTest.php
Closes #122 and is a replica of laravel/cashier-stripe#1129.
When on a generic trial but also having an active subscription, it will now return the ending date of the generic trial instead of the subscription.
=> [2.x] Fixed trial ends at

src/Price.php, tests/Unit/ProductPriceTest.php
Easily check if the price has tax:
```
$price->price()->hasTax();
```
In some countries sales tax is not required, this allows for easier conditionals.
=> `hasTax()` for price

src/Concerns/ManagesCustomer.php, src/Concerns/PerformsCharges.php, tests/Feature/ChargesTest.php
This fixes an issue with refunds where the response identifier wasn't properly located in the JSON response.
Fixes https://github.com/laravel/cashier-paddle/issues/130
=> [1.x] Fix refunds

tests/Feature/ChargesTest.php
This fixes an issue where a previous redirect by Paddle was used, now the direct url is returned for pay link responses.
=> Fix checkout url

.github/workflows/tests.yml, composer.json
This adds the same changes like https://github.com/laravel/cashier-stripe/pull/1280
=> [1.x] Allow moneyphp version 4

composer.json, tests/Feature/ChargesTest.php, tests/Feature/PricesTest.php
Simple change to also allow `spatie/url` in version 2.0, which raises the minimum to PHP 8.0 (and proper PHP 8.1 support respectively), but does not have any breaking changes, just feature updates.
People on PHP <8.0 can still use the 1.0 version.
=> Allow spatie/url 2.0

src/Events/SubscriptionPaymentSucceeded.php
Apparently this isn't always the promised type from the docs.
https://github.com/laravel/cashier-paddle/issues/158
=> [1.x] Fix type for event

src/Cashier.php
This will allow an underlying library to use the given locale in a custom formatter.
=> [1.x] Pass locale to custom format amount

.github/workflows/tests.yml, src/Payment.php, src/ProductPrice.php
By enabling deprecation throwing in tests, we can solve them early-on.
=> [1.x] Throw deprecations in tests

.github/CONTRIBUTING.md, src/Cashier.php, src/CashierFake.php, tests/Feature/ChargesTest.php, tests/Feature/ModifiersTest.php, tests/Feature/SubscriptionsTest.php, tests/Feature/WebhooksTest.php, tests/Unit/CashierFakeTest.php
This PR adds a way for users to easily fake events and API calls with a single command and a couple options for customizing the responses and asserting that certain events are dispatched.
Under the hood, `Cashier::fake()` creates a new instance of `CashierFake` which, upon creation, fakes API calls with `Http::fake()` and Cashier-provided events as well with `Event::fake()`. A user may customize this experience if they wish to override the defaults by providing an array with an endpoint as the key and a response as its value as such:
```php
Cashier::fake([
'subscription/create' => ['fake-response' => 'and its data']
]);
```
Internally, CashierFake will format this path into a paddle API call within the `retrieveEndpoint($path)` call which uses Cashier's `vendorsUrl` method and some …
=> Add a `fake` method to Cashier

composer.json
I've applied the same patch as @GrahamCampbell made for [cashier-stripe](https://github.com/laravel/cashier-stripe/pull/1114).
=> Replace heavy `symfony/intl` dependency

src/Subscription.php, tests/Unit/SubscriptionTest.php
This PR will make quantity methods on a subscription start throwing a `LogicException` when it's attempting to decrease the quantity to zero. This is not possible in Paddle. Right now, if anyone attempts this the code will throw a PaddleException with a message:
> One or more required arguments are missing
This PR will throw an exception faster before hitting the API and provide a more clear message.
=> [1.x] Do not allow updating quantities to zero

src/Subscription.php
I just think this one got missed, or their API has changed since this package was made.
As per their docs, it returns a string (I tested and it seems to be true)
Source: https://developer.paddle.com/api-reference/e33e0a714a05d-list-users#Responses
=> Modify return type of updateUrl and cancelUrl on Subscription

src/Modifier.php, src/Payment.php, src/Price.php, src/Receipt.php, tests/Feature/PaymentTest.php, tests/Unit/CashierTest.php
This fixes an issue where Japanese Yen amounts weren't displayed properly. Since Japanese Yen doesn't have cent amounts, they don't need the `* 100` modifier before being parsed into a money format. This PR checks if the currency is Japanese Yen and fixes the displayed value to the proper amount.
Fixes https://github.com/laravel/cashier-paddle/issues/183
=> Fix Japanese Yen amounts

src/Concerns/ManagesAmounts.php, src/Modifier.php, src/Payment.php, src/Price.php, src/Receipt.php
* introduce formatDecimalAmount to handle the format that paddle returns from api calls.
* move the amount logic into a new trait
This maintains backward compatibility as `formatAmount()` is unchanged.
=> Handle the paddle decimal amount

resources/views/js.blade.php
I noticed that I was getting 404s by Paddle on a staging environment. The 404s were on the product domain and caused by the fact that certain plan IDs could not be found.
I double checked the HTML to see if the environment was set correctly. Apparently the code for setting the environment to Sandbox environment was present. However, when running `Paddle.Environment.get()` in the console, it would return `production` as environment. 
I was able to pinpoint the issue to Livewire and the fact that Livewire v3 now introduces `__BLOCK__` comments in HTML around Blade `@if`'s:
Since the if-condition was inside a `<script>` tag, JavaScript doesn't know how to handle this comment well, and therefore the environment would never be set to sandbox. This PR solves the Livewire compatibility by …
=> [1.x] Fix Livewire support

src/Subscription.php
Fixes an issue with resuming paused subscriptions which are still in their pause grace period. Also adds the ability to pick the moment in time when the resume should take place.
=> Fix resume

src/Cashier.php, src/Payment.php, src/Subscription.php
- Adds a missing `useSubscriptionItemModel` method
- Adds a new `paymentMethodUpdateTransaction` method
- Removes the `nextBilledAt` method and re-adds the `lastPayment` and `nextPayment` methods
=> [2.x] Cashier Paddle v2: Minor updates
